spring:
    application:
        name: filmorate
    sql:
        init:
            mode: always
            encoding: UTF-8
    datasource:
        url: jdbc:h2:file:~/h2/filmorate/filmorate;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
        driverClassName: org.h2.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    h2:
        console:
            path: /h2-console
            settings.trace: false
            settings.web-allow-others: false

server:
    port: 8080
    error:
        include-stacktrace: never

logging.level.org.zalando.logbook: TRACE
